name: mobx_example
description: Examples for MobX
private: true

version: 1.0.0+1

environment:
  sdk: '>=2.1.1-dev <3.0.0'

dependencies:
  mobx: ^0.0.36

dev_dependencies:
  build_runner: ^1.2.5
  mobx_codegen: ^0.0.6

dependency_overrides:
  mobx:
    path: ../../mobx
  mobx_codegen:
    path: ../../mobx_codegen
