name: angular_todos
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.1.1
  mobx: ^0.0.37
  angular_mobx:
    path: ../../../angular_mobx
  store:
    path: ../store
dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.2.3
  build_web_compilers: ^1.1.0
  test: ^1.5.3
  pedantic: ^1.4.0
dependency_overrides:
  analyzer: ^0.34.0
