name: angular_mobx
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: vts <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.4.1
  mobx: ^0.0.36
  angular: ^5.2.0
dev_dependencies:
  pedantic: ^1.0.0
  angular_test: ^2.2.0
  build_runner: ^1.2.3
  build_test: any
  build_web_compilers: ^1.1.0
  pageloader: ^3.0.0
  test: ^1.5.3
  mobx_codegen: ^0.0.8
dependency_overrides:
  analyzer: ^0.34.0
