name: angular_github_search
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.12.0
  angular_mobx:
    path: ../../../angular_mobx
  github:
    path: ../../../../github.dart
  store:
    path: ../store
  mobx: ^0.0.36
dev_dependencies:
  angular_test: ^2.0.0
  build_runner: any
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
dependency_overrides:
  analyzer: ^0.34.0
